### ISSUE TITLE
Primary Navigation

### ISSUE THREAD

**Issue by jcaustrita** [jcaustrita/petrucela#2]
Have ZERO clue on how to tackle the nav... or make it into a hamburger menu for mobile... ZERO clue!

**Comment by jcaustrita** [comment]
yo...got the nav "working". gets really funky on breakdown but not sure how to handle that...

**Comment by nguyenj** [comment]
Commit what you have so I can check it out later.

**Comment by jcaustrita** [comment]
i think i have...i did a sync from what you did then have been working on it throughout the afternoon. should be good...

**Comment by nguyenj** [comment]
Hmm I don't see the update. Did you fill out a commit note and the commit it? Then maybe sync it?

**Comment by jcaustrita** [comment]
you see it now? i forgot to sync it up :)
